language: node_js
node_js:
- '6.11.3'
cache:
  directories:
  - node_modules
notifications:
  email: false
  slack:
    rooms:
      secure: So0FpcVmlVZ8HWQwVbZGDpV24vbEKjPO3IM1I2fpdZvdTd13L2HFrfv6vzsUWSFhfAE4YpKeRReoAEyWcvgz0Do6I1dOQ3EvK8wYSes+6lrQVRdKzQj+1kapenxPxy+pMHFyFs0g5ZUVgUML2wZFZVS0QY95tUkKQX8UzAwIKW3nB0L3HjtYFBT8PF+wVMUk1ac86yGN5QDftiAgquhKngvjJFx31buDihhGRoGWWXTVkF2uDGgInThFL5ckXTRihghoRZvJ/IHtRHNrCj+DJlokleh0PqiThdYj8IXLMQmNvhCvu3qwBrIyxwrCYRgf1Ur6OGki3f+edacowwCTMv7si+McoP1JX7/+NUh7GMIc+3mnb6D1Ab5+NtoVcoAH94MY2SlOsAdzw5yeQBa1gDuNOayO0QbgLEVFuPUU1zTzchm30hHFemLn8EMc6DCQtpVU1NyOrF3zcz/KUrOK+Ds9bCKDAu440syFr4CX9W2wSd71MZimOi1u1ExkKJh6NQuA0zoOVXPFqJW7uQ3SSZEgxNi7J4O2FfYhvlqt2HnY/Y31M2vTKhSfLx4tD0/9qH9YleV0Gy/DafSMFrFoBIurNXaZmPD5hlITEsJ4y6UtOKsn2OxJS5+95CG9Obr6GegH0bHT9+xKIoOh8eANndOpcZivIb+pyvFFw6QMIDQ=
    on_success: never
    on_failure: always
    on_pull_requests: false
before_script:
- npm prune
after_success:
- npm run coveralls
- npm run semantic-release
